default: &default
  aws_region: 'us-east-1'

development:
  <<: *default
  preservation_bucket_name: 'example-dev-bucket'
  aws_access_key_id: 'access_key_id'
  aws_secret_access_key: 'secret_access_key'

test:
  <<: *default
  preservation_bucket_name: 'example-test-bucket'
  aws_access_key_id: 'access_key_id'
  aws_secret_access_key: 'secret_access_key'
